### ISSUE TITLE
problems with install

### ISSUE THREAD

**Issue by GiWeMX** [Itz-Abhishek-Tiwari/Abyssal-Wave#5]
~ took 18s 
❯ Hyde theme import Abyssal-Wave 'https://github.com/Itz-Abhishek-Tiwari/Abyssal-Wave'
Select a Branch
1) Abyssalhorizon
2) main
#? 2
Directory /home/giwemx/.cache/hyde/themepatcher/Itz-Abhishek-Tiwari.main.Abyssal-Wave already exists. Using existing directory.
Patching --// Abyssal-Wave //-- from /home/giwemx/.cache/hyde/themepatcher/Itz-Abhishek-Tiwari.main.Abyssal-Wave

[!!] .config/hyde/themes/Abyssal-Wave/gtk/gtk3.theme --> do not exist in /home/giwemx/.cache/hyde/themepatcher/Itz-Abhishek-Tiwari.main.Abyssal-Wave/Configs/
[!!] .config/hyde/themes/Abyssal-Wave/gtk/gtk4.theme --> do not exist in /home/giwemx/.cache/hyde/themepatcher/Itz-Abhishek-Tiwari.main.Abyssal-Wave/Configs/
[OK] .config/hyde/themes/Abyssal-Wave/hypr.theme
[OK] .config/hyde/themes/Abyssal-Wave/kitty.theme
[OK] .config/hyde/themes/Abyssal-Wave/kvantum/kvantum.theme
[OK] .config/hyde/themes/Abyssal-Wave/kvantum/kvconfig.theme
[OK] .config/hyde/themes/Abyssal-Wave/rofi.theme
[OK] .config/hyde/themes/Abyssal-Wave/waybar.theme
[wallpapers]
/wallpapers/bg-1.png

[OK] wallpapers :: [count] 1 (.gif+.jpg+.jpeg+.png)
[OK] hypr.theme :: [gtk] $GTK_THEME
[OK] ../*.tar.* :: [gtk] 
[ERROR] gtk-theme set in hypr.theme does not exist in Gtk_*.tar.*
[OK] hypr.theme :: [icon] $ICON_THEME
[OK] ../*.tar.* :: [icon] 
[ERROR] icon-theme set in hypr.theme does not exist in Icon_*.tar.*
[!!] hypr.theme :: [cursor] Not Found
[!!] hypr.theme :: [sddm] Not Found
[!!] hypr.theme :: [font] Not Found
[!!] hypr.theme :: [document-font] Not Found

**Comment by Itz-Abhishek-Tiwari** [comment]
select the main branch  by pressing 2 and enter
